### ISSUE TITLE
Error with Protagonist when installing snowboard

### ISSUE THREAD

**Issue by MiguelCorti** [bukalapak/snowboard#119]
Maybe this issue does not belong here, if it doesn't I'm sorry!

I'm trying to install snowboard globally for the first time on my notebook (I have succeed a while ago on a previous version on my desktop). I tried downloading both the latest version (4.1.0) and an older version (3.7.5). Both get lots of warnings and errors when installing protagonist@2.1.0, **4.1.0** gets stuck at `node-gyp rebuild`, **3.7.5** finishes installing but doesn't work when trying to use the `html` command. I'll post here a screenshot of the error when installing **4.1.0** on my terminal, and the last 40 lines of the npm log:

**Node Version:** 13.11.0
**Node Gyp Version:** 5.0.7
**Npm Version:** 6.13.7

![image](https://user-images.githubusercontent.com/5075086/78717420-f2433480-78f6-11ea-93d5-5d5ba87370b1.png)

```
20230 warn enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/miguel/.nvm/versions/node/v13.11.0/lib/node_modules/snowboard/node_modules/fsevents/node_modules/signal-exit' -> '/home/miguel/.nvm/versions/node/v13.11.0/lib/node_modules/snowboard/node_modules/fsevents/node_modules/.signal-exit.DELETE'
20231 verbose enoent SKIPPING OPTIONAL DEPENDENCY: This is related to npm not being able to find a file.
20231 verbose enoent SKIPPING OPTIONAL DEPENDENCY:
20232 warn optional SKIPPING OPTIONAL DEPENDENCY: strip-json-comments@2.0.1 (node_modules/snowboard/node_modules/fsevents/node_modules/strip-json-comments):
20233 warn enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/miguel/.nvm/versions/node/v13.11.0/lib/node_modules/snowboard/node_modules/fsevents/node_modules/strip-json-comments' -> '/home/miguel/.nvm/versions/node/v13.11.0/lib/node_modules/snowboard/node_modules/fsevents/node_modules/.strip-json-comments.DELETE'
20234 verbose enoent SKIPPING OPTIONAL DEPENDENCY: This is related to npm not being able to find a file.
20234 verbose enoent SKIPPING OPTIONAL DEPENDENCY:
20235 warn optional SKIPPING OPTIONAL DEPENDENCY: util-deprecate@1.0.2 (node_modules/snowboard/node_modules/fsevents/node_modules/util-deprecate):
20236 warn enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/miguel/.nvm/versions/node/v13.11.0/lib/node_modules/snowboard/node_modules/fsevents/node_modules/util-deprecate' -> '/home/miguel/.nvm/versions/node/v13.11.0/lib/node_modules/snowboard/node_modules/fsevents/node_modules/.util-deprecate.DELETE'
20237 verbose enoent SKIPPING OPTIONAL DEPENDENCY: This is related to npm not being able to find a file.
20237 verbose enoent SKIPPING OPTIONAL DEPENDENCY:
20238 warn optional SKIPPING OPTIONAL DEPENDENCY: wrappy@1.0.2 (node_modules/snowboard/node_modules/fsevents/node_modules/wrappy):
20239 warn enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/miguel/.nvm/versions/node/v13.11.0/lib/node_modules/snowboard/node_modules/fsevents/node_modules/wrappy' -> '/home/miguel/.nvm/versions/node/v13.11.0/lib/node_modules/snowboard/node_modules/fsevents/node_modules/.wrappy.DELETE'
20240 verbose enoent SKIPPING OPTIONAL DEPENDENCY: This is related to npm not being able to find a file.
20240 verbose enoent SKIPPING OPTIONAL DEPENDENCY:
20241 warn optional SKIPPING OPTIONAL DEPENDENCY: yallist@3.1.1 (node_modules/snowboard/node_modules/fsevents/node_modules/yallist):
20242 warn enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/miguel/.nvm/versions/node/v13.11.0/lib/node_modules/snowboard/node_modules/fsevents/node_modules/yallist' -> '/home/miguel/.nvm/versions/node/v13.11.0/lib/node_modules/snowboard/node_modules/fsevents/node_modules/.yallist.DELETE'
20243 verbose enoent SKIPPING OPTIONAL DEPENDENCY: This is related to npm not being able to find a file.
20243 verbose enoent SKIPPING OPTIONAL DEPENDENCY:
20244 verbose stack Error: protagonist@2.1.0 install: `node-gyp rebuild`
20244 verbose stack Exit status 1
20244 verbose stack     at EventEmitter.<anonymous> (/home/miguel/.nvm/versions/node/v13.11.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
20244 verbose stack     at EventEmitter.emit (events.js:315:20)
20244 verbose stack     at ChildProcess.<anonymous> (/home/miguel/.nvm/versions/node/v13.11.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
20244 verbose stack     at ChildProcess.emit (events.js:315:20)
20244 verbose stack     at maybeClose (internal/child_process.js:1026:16)
20244 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
20245 verbose pkgid protagonist@2.1.0
20246 verbose cwd /home/miguel/Documents/Trampolin/AppBackend
20247 verbose Linux 4.4.0-176-generic
20248 verbose argv "/home/miguel/.nvm/versions/node/v13.11.0/bin/node" "/home/miguel/.nvm/versions/node/v13.11.0/bin/npm" "i" "-g" "snowboard@4.1.0"
20249 verbose node v13.11.0
20250 verbose npm  v6.13.7
20251 error code ELIFECYCLE
20252 error errno 1
20253 error protagonist@2.1.0 install: `node-gyp rebuild`
20253 error Exit status 1
20254 error Failed at the protagonist@2.1.0 install script.
20254 error This is probably not a problem with npm. There is likely additional logging output above.
20255 verbose exit [ 1, true ]
```
Any idea as to why this happens? 

Thanks! I'll attach the full log below if it's of use, and if needed I can move this issue to protagonist repo.

[2020-04-07T20_33_39_184Z-debug.log](https://github.com/bukalapak/snowboard/files/4446974/2020-04-07T20_33_39_184Z-debug.log)

**Comment by subosito** [comment]
Protagonist does not play well with Node 13; please try using Node 12 and Python 2. Feel free to reopen if the issue persists.

**Comment by rafgugi** [comment]
I have same issue using   
**Node Version**: 12.18.0  
**Npm Version**: 6.14.8  

fixed using `$ sudo npm i -g snowboard --unsafe-perm=true --allow-root`

**Comment by u4989190** [comment]
> 
> fixed using `$ sudo npm i -g snowboard --unsafe-perm=true --allow-root`

not working for me.
