### ISSUE TITLE
Global Snowboard installation fails

### ISSUE THREAD

**Issue by X-Ray-Jin** [bukalapak/snowboard#169]
Hey guys, I am trying to install Snowboard globally and I just can't get it to work.

I am on Windows 10 and I used nvm-windows@1.1.7 to install node@14.15.4 (latest LTS) and npm@6.14.10.
Then I run `npm install -g snowboard` which starts off well and then I get this:

<details><summary>Errors and warnings</summary>
<p>
npm install -g snowboard<br>
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated<br>
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated<br>
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.<br>
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.<br>
npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410<br>
C:\Program Files\nodejs\snowboard -> C:\Program Files\nodejs\node_modules\snowboard\bin\run

> protagonist@2.2.1 install C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist
> node-gyp rebuild

C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist>if not defined npm_config_node_gyp (node "C:\Users\toggi\AppData\Roaming\nvm\v14.15.4\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\toggi\AppData\Roaming\nvm\v14.15.4\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Warning: Missing input files:
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\refract\dsd\test-Select.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\utils\test-Utf8.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\utils\so\test-YamlIo.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\test-VisitorUtils.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\test\test-ParameterParser.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\test\test-ParametersParser.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\test\test-ResourceGroupParser.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\utils\so\test-JsonIo.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\parser\test-Recover.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\refract\dsd\test-Ref.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\test\test-SymbolIdentifier.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\test-ElementFactoryTest.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\test\test-MSONMixinParser.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\test-ElementDataTest.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\test\test-snowcrash.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\test-sourceMapToLineColumn.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\ext\markdown-parser\test\test-libmarkdownparser.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\test\test-Signature.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\refract\test-InfoElementsUtils.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\refract\test-JsonSchema.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\test-ElementComparator.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\test\test-RegexMatch.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\refract\dsd\test-Holder.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\refract\dsd\test-String.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\test\test-ValuesParser.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\refract\dsd\test-Number.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\test\test-MSONPropertyMemberParser.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\draftertest.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\test\test-BlueprintUtility.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\refract\dsd\test-Element.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\src\Version.h
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\test\test-MSONNamedTypeParser.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\test\test-Indentation.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\test-RefractSourceMapTest.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\refract\test-Utils.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\test-ElementInfoUtils.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\test\test-AssetParser.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\ext\markdown-parser\test\test-MarkdownParser.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\refract\dsd\test-Bool.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\refract\dsd\test-Object.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\refract\dsd\test-Null.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\refract\dsd\test-Array.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\test\test-StringUtility.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\test-RefractDataStructureTest.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\refract\dsd\test-InfoElements.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\test\test-MSONUtility.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\test\test-ActionParser.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\test\test-DataStructureGroupParser.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\test-CAPI.c
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\test\test-MSONOneOfParser.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\test\test-MSONValueMemberParser.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\refract\dsd\test-Enum.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\refract\test-ElementSize.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\src\parser\UriTemplateParser.h
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\test\test-PayloadParser.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\test-RenderTest.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\parser\test-UriTemplate.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\parser\test-MediaType.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\test\test-Warnings.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\refract\dsd\test-Member.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\test-ContentTypeMatcher.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\test\test-ModelTable.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\backend\test-MediaTypeS11.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\test-RefractParseResultTest.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\refract\dsd\test-Extend.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\refract\dsd\test-Option.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\test\test-MSONParameterParser.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\test-drafter.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\ext\markdown-parser\test\test-ByteBuffer.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\test\test-SectionParser.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\refract\test-JsonValue.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\test\test-MSONTypeSectionParser.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\test-RefractAPITest.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\test\test-RelationParser.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\test-Serialize.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\test-ApplyVisitorTest.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\ctesting.c
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\test\test-UriTemplateParser.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\test-SyntaxIssuesTest.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\ctesting.h
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\test\test-AttributesParser.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\test\test-Blueprint.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\test\test-HeadersParser.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\test\test-BlueprintParser.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\test-SchemaTest.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\test-ExtendElementTest.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\test\performance\perf-snowcrash.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\ext\snowcrash\test\test-ResourceParser.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\refract\test-Cardinal.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\test-CircularReferenceTest.cc
C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\..\..\drafter\test\test-OneOfTest.cc
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
  drafter.cc
  options.cc
  Serialize.cc
  SerializeKey.cc
  SerializeResult.cc
  RefractAPI.cc
  MsonTypeSectionToApie.cc
  MsonMemberToApie.cc
  MsonOneOfSectionToApie.cc
  RefractDataStructure.cc
c:\program files\nodejs\node_modules\snowboard\node_modules\protagonist\drafter\ext\snowcrash\src\just.h(21): error C24
40: "noexcept": "T" kann nicht in "bool" konvertiert werden [C:\Program Files\nodejs\node_modules\snowboard\node_module
s\protagonist\build\drafter\libdrafter.vcxproj]
          with
          [
              T=mson::Elements
          ] (Quelldatei wird kompiliert ..\..\drafter\src\MsonMemberToApie.cc)
  c:\program files\nodejs\node_modules\snowboard\node_modules\protagonist\drafter\ext\snowcrash\src\just.h(21): note: K
  ein benutzerdefinierter Konvertierungsoperator verfügbar, der diese Konvertierung durchführen kann, oder der Operator
   kann nicht aufgerufen werden (Quelldatei wird kompiliert ..\..\drafter\src\MsonMemberToApie.cc)
  c:\program files\nodejs\node_modules\snowboard\node_modules\protagonist\drafter\ext\variant\include\mpark\variant.hpp
  (1165): note: Siehe Verweis auf die Instanziierung der gerade kompilierten Funktions-Vorlage "mpark::detail::alt<4,T>
  ::alt<T>(mpark::in_place_t,T &&)".
          with
          [
              T=mson::Element::OneOfSection
          ] (Quelldatei wird kompiliert ..\..\drafter\src\MsonMemberToApie.cc)
  c:\program files\nodejs\node_modules\snowboard\node_modules\protagonist\drafter\ext\variant\include\mpark\variant.hpp
  (1165): note: Siehe Verweis auf die Instanziierung der gerade kompilierten Funktions-Vorlage "mpark::detail::alt<4,T>
  ::alt<T>(mpark::in_place_t,T &&)".
          with
          [
              T=mson::Element::OneOfSection
          ] (Quelldatei wird kompiliert ..\..\drafter\src\MsonMemberToApie.cc)
  c:\program files\nodejs\node_modules\snowboard\node_modules\protagonist\drafter\ext\variant\include\mpark\variant.hpp
  (1280): note: Siehe Verweis auf die Instanziierung der gerade kompilierten Funktions-Vorlage "T &mpark::detail::const
  ructor<mpark::detail::traits<mson::Element::Empty,mson::Element::PropertyMemberSection,mson::Element::ValueMemberSect
  ion,mson::Element::MixinSection,mson::Element::OneOfSection,mson::Element::GroupSection>>::construct_alt<4,T,T>(mpark
  ::detail::alt<4,T> &,T &&)".
          with
          [
              T=mson::Element::OneOfSection
          ] (Quelldatei wird kompiliert ..\..\drafter\src\MsonMemberToApie.cc)
  c:\program files\nodejs\node_modules\snowboard\node_modules\protagonist\drafter\ext\variant\include\mpark\variant.hpp
  (1279): note: Siehe Verweis auf die Instanziierung der gerade kompilierten Funktions-Vorlage "T &mpark::detail::const
  ructor<mpark::detail::traits<mson::Element::Empty,mson::Element::PropertyMemberSection,mson::Element::ValueMemberSect
  ion,mson::Element::MixinSection,mson::Element::OneOfSection,mson::Element::GroupSection>>::construct_alt<4,T,T>(mpark
  ::detail::alt<4,T> &,T &&)".
          with
          [
              T=mson::Element::OneOfSection
          ] (Quelldatei wird kompiliert ..\..\drafter\src\MsonMemberToApie.cc)
  c:\program files\nodejs\node_modules\snowboard\node_modules\protagonist\drafter\ext\variant\include\mpark\variant.hpp
  (1311): note: Siehe Verweis auf die Instanziierung der gerade kompilierten Funktions-Vorlage "T &mpark::detail::assig
  nment<mpark::detail::traits<mson::Element::Empty,mson::Element::PropertyMemberSection,mson::Element::ValueMemberSecti
  on,mson::Element::MixinSection,mson::Element::OneOfSection,mson::Element::GroupSection>>::emplace<4,T>(T &&)".
          with
          [
              T=mson::Element::OneOfSection
          ] (Quelldatei wird kompiliert ..\..\drafter\src\MsonMemberToApie.cc)
  c:\program files\nodejs\node_modules\snowboard\node_modules\protagonist\drafter\ext\variant\include\mpark\variant.hpp
  (1311): note: Siehe Verweis auf die Instanziierung der gerade kompilierten Funktions-Vorlage "T &mpark::detail::assig
  nment<mpark::detail::traits<mson::Element::Empty,mson::Element::PropertyMemberSection,mson::Element::ValueMemberSecti
  on,mson::Element::MixinSection,mson::Element::OneOfSection,mson::Element::GroupSection>>::emplace<4,T>(T &&)".
          with
          [
              T=mson::Element::OneOfSection
          ] (Quelldatei wird kompiliert ..\..\drafter\src\MsonMemberToApie.cc)
  c:\program files\nodejs\node_modules\snowboard\node_modules\protagonist\drafter\ext\variant\include\mpark\variant.hpp
  (1437): note: Siehe Verweis auf die Instanziierung der gerade kompilierten Funktions-Vorlage "void mpark::detail::ass
  ignment<mpark::detail::traits<mson::Element::Empty,mson::Element::PropertyMemberSection,mson::Element::ValueMemberSec
  tion,mson::Element::MixinSection,mson::Element::OneOfSection,mson::Element::GroupSection>>::assign_alt<4,T,T>(mpark::
  detail::alt<4,T> &,Arg &&)".
          with
          [
              T=mson::Element::OneOfSection,
              Arg=mson::just<mson::Elements,mson::one_of_tag>
          ] (Quelldatei wird kompiliert ..\..\drafter\src\MsonMemberToApie.cc)
  c:\program files\nodejs\node_modules\snowboard\node_modules\protagonist\drafter\ext\variant\include\mpark\variant.hpp
  (1436): note: Siehe Verweis auf die Instanziierung der gerade kompilierten Funktions-Vorlage "void mpark::detail::ass
  ignment<mpark::detail::traits<mson::Element::Empty,mson::Element::PropertyMemberSection,mson::Element::ValueMemberSec
  tion,mson::Element::MixinSection,mson::Element::OneOfSection,mson::Element::GroupSection>>::assign_alt<4,T,T>(mpark::
  detail::alt<4,T> &,Arg &&)".
          with
          [
              T=mson::Element::OneOfSection,
              Arg=mson::just<mson::Elements,mson::one_of_tag>
          ] (Quelldatei wird kompiliert ..\..\drafter\src\MsonMemberToApie.cc)
  c:\program files\nodejs\node_modules\snowboard\node_modules\protagonist\drafter\ext\variant\include\mpark\variant.hpp
  (1657): note: Siehe Verweis auf die Instanziierung der gerade kompilierten Funktions-Vorlage "void mpark::detail::imp
  l<mson::Element::Empty,mson::Element::PropertyMemberSection,mson::Element::ValueMemberSection,mson::Element::MixinSec
  tion,mson::Element::OneOfSection,mson::Element::GroupSection>::assign<4,T>(Arg &&)".
          with
          [
              T=mson::just<mson::Elements,mson::one_of_tag>,
              Arg=mson::just<mson::Elements,mson::one_of_tag>
          ] (Quelldatei wird kompiliert ..\..\drafter\src\MsonMemberToApie.cc)
  c:\program files\nodejs\node_modules\snowboard\node_modules\protagonist\drafter\ext\variant\include\mpark\variant.hpp
  (1657): note: Siehe Verweis auf die Instanziierung der gerade kompilierten Funktions-Vorlage "void mpark::detail::imp
  l<mson::Element::Empty,mson::Element::PropertyMemberSection,mson::Element::ValueMemberSection,mson::Element::MixinSec
  tion,mson::Element::OneOfSection,mson::Element::GroupSection>::assign<4,T>(Arg &&)".
          with
          [
              T=mson::just<mson::Elements,mson::one_of_tag>,
              Arg=mson::just<mson::Elements,mson::one_of_tag>
          ] (Quelldatei wird kompiliert ..\..\drafter\src\MsonMemberToApie.cc)
  c:\program files\nodejs\node_modules\snowboard\node_modules\protagonist\drafter\ext\snowcrash\src\mson.h(412): note:
  Siehe Verweis auf die Instanziierung der gerade kompilierten Funktions-Vorlage "mpark::variant<mson::Element::Empty,m
  son::Element::PropertyMemberSection,mson::Element::ValueMemberSection,mson::Element::MixinSection,mson::Element::OneO
  fSection,mson::Element::GroupSection> &mpark::variant<mson::Element::Empty,mson::Element::PropertyMemberSection,mson:
  :Element::ValueMemberSection,mson::Element::MixinSection,mson::Element::OneOfSection,mson::Element::GroupSection>::op
  erator =<mson::just<mson::Elements,mson::one_of_tag>,0,4,mson::just<mson::Elements,mson::one_of_tag>,0>(Arg &&) noexc
  ept".
          with
          [
              Arg=mson::just<mson::Elements,mson::one_of_tag>
          ] (Quelldatei wird kompiliert ..\..\drafter\src\MsonMemberToApie.cc)
  c:\program files\nodejs\node_modules\snowboard\node_modules\protagonist\drafter\ext\snowcrash\src\mson.h(412): note:
  Siehe Verweis auf die Instanziierung der gerade kompilierten Funktions-Vorlage "mpark::variant<mson::Element::Empty,m
  son::Element::PropertyMemberSection,mson::Element::ValueMemberSection,mson::Element::MixinSection,mson::Element::OneO
  fSection,mson::Element::GroupSection> &mpark::variant<mson::Element::Empty,mson::Element::PropertyMemberSection,mson:
  :Element::ValueMemberSection,mson::Element::MixinSection,mson::Element::OneOfSection,mson::Element::GroupSection>::op
  erator =<mson::just<mson::Elements,mson::one_of_tag>,0,4,mson::just<mson::Elements,mson::one_of_tag>,0>(Arg &&) noexc
  ept".
          with
          [
              Arg=mson::just<mson::Elements,mson::one_of_tag>
          ] (Quelldatei wird kompiliert ..\..\drafter\src\MsonMemberToApie.cc)
c:\program files\nodejs\node_modules\snowboard\node_modules\protagonist\drafter\ext\snowcrash\src\just.h(21): error C21
31: Ausdruck wurde nicht zu einer Konstanten ausgewertet. (Quelldatei wird kompiliert ..\..\drafter\src\MsonMemberToApi
e.cc) [C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist\build\drafter\libdrafter.vcxproj]
  c:\program files\nodejs\node_modules\snowboard\node_modules\protagonist\drafter\ext\snowcrash\src\just.h(21): note: E
  in nicht konstanter (Teil)ausdruck wurde gefunden. (Quelldatei wird kompiliert ..\..\drafter\src\MsonMemberToApie.cc)
  RefractSourceMap.cc
</p>
</details>

Followed by lot more of these notifications and this is the final error output:
```<
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\toggi\AppData\Roaming\nvm\v14.15.4\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\toggi\\AppData\\Roaming\\nvm\\v14.15.4\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Program Files\nodejs\node_modules\snowboard\node_modules\protagonist
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules\snowboard\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\snowboard\node_modules\watchpack-chokidar2\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\snowboard\node_modules\webpack-dev-server\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! protagonist@2.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the protagonist@2.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\toggi\AppData\Roaming\npm-cache\_logs\2021-01-18T11_11_00_809Z-debug.log
>```

Anyone an idea how to fix that? I tried installing Protagonist and Node-Gyp in various versions manually but that doesn't help. Tried as normal and as admin user. Windows build tools are installed, too.

**Comment by u4989190** [comment]
you may take a look at this issue [119](https://github.com/bukalapak/snowboard/issues/119)
or you may run snowboard in docker instead installing it on your local machine.

**Comment by u4989190** [comment]
@X-Ray-Jin 
thank you for your recommendation. I managed to install snowboard at last(not on windows though, I did it on wsl2), but yet failed to parse the apib file. it seems that other team member, who is using Mac, edited the file with LF breaks and since windows is CRLF, it just don't work out. I just give up and asked him to generate a static html for me so I will not parse the apib files.

I am using this API blueprint only because our client choose the tech stack. for those projects where I am the leader, I usually go on with OPEN API, and if you are building REST API endpoints, I strongly encourage you take a look at it. it goes well with a lot of tools which are well-developed, such as swagger, stoplight etc, and the community is thriving. anyway, good luck!
